pos_bahrain/public/js/batch_quick_entry.js

- make expiry_date mandatory when set in Item

Batch: fix error during insert

---

pos_bahrain/api/item.py
pos_bahrain/public/js/pos_page_js.js

POS: send only in-stocked batches

---

pos_bahrain/pos_bahrain/report/customer_item_wise_sales/customer_item_wise_sales.json
pos_bahrain/pos_bahrain/report/customer_item_wise_sales/customer_item_wise_sales.py
pos_bahrain/pos_bahrain/report/customer_sales_summary/customer_sales_summary.html
pos_bahrain/pos_bahrain/report/customer_sales_summary/customer_sales_summary.json
pos_bahrain/pos_bahrain/report/item_wise_periodic_sales_for_customer/item_wise_periodic_sales_for_customer.html
pos_bahrain/pos_bahrain/report/item_wise_periodic_sales_for_customer/item_wise_periodic_sales_for_customer.json
pos_bahrain/pos_bahrain/report/item_wise_periodic_sales_for_customer/item_wise_periodic_sales_for_customer.py
pos_bahrain/pos_bahrain/report/item_wise_sales_returns/item_wise_sales_returns.json
pos_bahrain/pos_bahrain/report/item_wise_sales_returns/item_wise_sales_returns.py
pos_bahrain/pos_bahrain/report/sales_person_item_wise_sales/sales_person_item_wise_sales.json
pos_bahrain/pos_bahrain/report/sales_person_item_wise_sales/sales_person_item_wise_sales.py
pos_bahrain/pos_bahrain/report/simple_purchase_register/simple_purchase_register.js
pos_bahrain/pos_bahrain/report/simple_purchase_register/simple_purchase_register.json
pos_bahrain/pos_bahrain/report/simple_purchase_register/simple_purchase_register.py
pos_bahrain/pos_bahrain/report/simple_sales_register/simple_sales_register.js
pos_bahrain/pos_bahrain/report/simple_sales_register/simple_sales_register.json
pos_bahrain/pos_bahrain/report/simple_sales_register/simple_sales_register.py
pos_bahrain/public/js/pos_page_js.js
pos_bahrain/public/js/stock_entry.js

PR #51, #52 and #53 not present in master.

Purchase / Sales Register

---

pos_bahrain/pos_bahrain/report/sales_person_item_wise_sales/sales_person_item_wise_sales.py
pos_bahrain/public/js/pos_page_js.js

Reverts f-9t9it/pos_bahrain#57

Revert " POS: show return checkbox above numeric keypad"

---

pos_bahrain/pos_bahrain/doctype/pos_closing_voucher/pos_closing_voucher.js
pos_bahrain/pos_bahrain/doctype/pos_closing_voucher/pos_closing_voucher.json

POS Closing Voucher: add returns net total

---

pos_bahrain/pos_bahrain/report/daily_sales_summary/daily_sales_summary.py

Daily Sales Summary: reduce cash amount by change

---

pos_bahrain/public/js/pos_page_js.js

POS: fix batch not being set

---

pos_bahrain/public/js/batch_quick_entry.js
pos_bahrain/public/js/pos_page_js.js

fixes and updates

---

pos_bahrain/pos_bahrain/doctype/opening_cash/opening_cash.py

fix: indetation issue

---

pos_bahrain/api/get_item_details.py
pos_bahrain/pos_bahrain/doctype/pos_closing_voucher/pos_closing_voucher.py
pos_bahrain/pos_bahrain/report/cheque_summary/cheque_summary.js
pos_bahrain/pos_bahrain/report/cheque_summary/cheque_summary.json
pos_bahrain/pos_bahrain/report/cheque_summary/cheque_summary.py

feat(report): create Cheque Summary

---

pos_bahrain/pos_bahrain/report/cash_account/cash_account.py
pos_bahrain/public/js/addons/index.js
pos_bahrain/public/js/addons/withBatchField.js
pos_bahrain/public/js/addons/withIdx.js
pos_bahrain/public/js/addons/withStockQty.js
pos_bahrain/public/js/addons/withStockValidator.js
pos_bahrain/public/js/pos_page_js.js

- Cash Account (Report): Invoice merge debit and credit
- Validator (POS): Add qty check actual_qty
- Update add_to_cart logic

Customizations

---

pos_bahrain/public/js/addons/withAsyncAddToCart.js

Reverts f-9t9it/pos_bahrain#119

Revert "fix: item undefined batch_no added to cart"

---

pos_bahrain/public/js/addons/withUom.js

- code superceded by server override hook

fix(pos): customer wise price

---

pos_bahrain/public/js/pos_page_js.js

Explanation
-
There could be an instance where syncing happens (this.si_docs will get replaced) and a user creates an invoice (create_invoice() could be updating to the localStorage using this.si_docs), at the same time. 
Instead of replacing for `sync_sales_invoice`, create another local instance to use it for syncing

fix: store data sync to local variables

---

pos_bahrain/api/gl_payment.py

fix: typo in error msg

---

pos_bahrain/public/js/addons/withAsyncAddToCart.js

**Motivation**
There are times that we need to check for items to be added on the cart. This function is useful for park management. e.g. check the item whether for resident conditions.

feat(withAsyncAddToCart): validate_add_to_cart

---

pos_bahrain/pos_bahrain/report/stock_balance_summary/stock_balance_summary.js
pos_bahrain/pos_bahrain/report/stock_balance_summary/stock_balance_summary.json
pos_bahrain/pos_bahrain/report/stock_balance_summary/stock_balance_summary.py

WIP: feat(report): added `Stock Balance Summary`

---

pos_bahrain/config/pos_bahrain.py

feat(config): added VAT Reports

---

pos_bahrain/pos_bahrain/report/vat_on_sales_per_gcc/vat_on_sales_per_gcc.py
pos_bahrain/public/js/reports/vat_on_sales_per_gcc.js
pos_bahrain/public/js/reports/vat_return.js

feat(reports): VAT DateRange to Dates (from_date, to_date)

---

pos_bahrain/pos_bahrain/report/hourly_sales/hourly_sales.js
pos_bahrain/pos_bahrain/report/hourly_sales/hourly_sales.json
pos_bahrain/pos_bahrain/report/hourly_sales/hourly_sales.py

feat(report): added Hourly Sales

---

pos_bahrain/pos_bahrain/report/vat_on_sales_per_gcc/vat_on_sales_per_gcc.py
pos_bahrain/public/js/addons/withStockQty.js

From:
https://github.com/f-9t9it/pos_bahrain/pull/230

fix: vat_on_sales_per gcc and batch details qty

---

pos_bahrain/api/item.py
pos_bahrain/public/js/addons/index.js
pos_bahrain/public/js/addons/withCustomerContacts.js

**Overview**
- In order to use the phone numbers, you need to set it on `Contact` linked to `Customer`.
- These phone numbers will be fetched to offline POS.
- On JS Print Format, you have to put `{{ __phone }}`

feat: customer contacts

---

pos_bahrain/api/quotation.py
pos_bahrain/hooks.py
pos_bahrain/public/js/quotation.js

Lacks: Update quotation status

feat: quotation to sales invoice

---

pos_bahrain/public/js/price_list.js

Reverts f-9t9it/pos_bahrain#307
Conflicting on V11

Revert "fix: price list not getting rates"

---

pos_bahrain/public/js/scripts/sales_invoice.js

feat(sales_invoice): pos return / credit note

---

pos_bahrain/doc_events/payment_entry.py

fixed sql error with payment entry when payment entry was made from purchase order

updated ref error payment entry

---

pos_bahrain/api/price_list.py
pos_bahrain/public/js/price_list.js

Updated price list fetching func - fixed error when there is no price list selected or selected price list is removed after activating the field.
Removed error when there is no default price list for the item and any price list is selected.

Updated price list fetching func.

---

pos_bahrain/public/js/price_list.js

fixed the issue where rate wouldn't show up on price list search  result on sals order and sales invoice item table.

Updated price_list.js

---

pos_bahrain/pos_bahrain/doctype/pos_closing_voucher/pos_closing_voucher.py

updated pos closing voucher to fetch payment entries based on pos profile and cashier name, if no cashier is selected, then pe is fetched using only pos profile

updated pos closing voucher

---

pos_bahrain/pos_bahrain/report/sales_gross_profit/sales_gross_profit.py

updated sales gross profit report. fixed issue with calculating amount before discount,, discount and amount after discount

fix: updates sales gross profit

---

pos_bahrain/public/js/sales_invoice.js

updated sales invoicce js to allow amending offline pos name

Updated sales invoice js

---

README.md
pos_bahrain/__init__.py
pos_bahrain/pos_bahrain/doctype/pos_closing_voucher/pos_closing_voucher.py
pos_bahrain/public/js/sales_invoice.js

Fixed POS Closing voucher bug where all payment entry was grouped by mode of payment in pe table

FIX: Updated POS Closing Voucher PE Table

---

README.md
pos_bahrain/__init__.py
pos_bahrain/api/price_checker.py

(1) Updated price checker API to include VAT rate and item rate with VAT in API Response.
(2) Updated Price checker API priority

Updated Price Checker API

---

README.md
pos_bahrain/__init__.py
pos_bahrain/api/price_checker.py
pos_bahrain/pos_bahrain/doctype/day_closing_voucher/day_closing_voucher.py
pos_bahrain/pos_bahrain/doctype/pos_closing_voucher/pos_closing_voucher.py

Updated price checker API priority.

Updated price checker API priority.

---

pos_bahrain/fixtures/custom_field.json

Updated pb_phone field type

---

pos_bahrain/fixtures/custom_field.json

updated custom field pb_description for sales invoice - set fetch if empty to 1 by default

Updated Custom field.json

---

README.md
pos_bahrain/__init__.py
pos_bahrain/hooks.py
pos_bahrain/pos_bahrain/doctype/pos_bahrain_settings/pos_bahrain_settings.json

option to disable autodeleting batch
Added option to disable core feature of auto deleting batches when a purchase receipt is cancelled

Version 12

---

pos_bahrain/config/pos_bahrain.py
pos_bahrain/pos_bahrain/report/branch_stock_and_value/branch_stock_and_value.js
pos_bahrain/pos_bahrain/report/branch_stock_and_value/branch_stock_and_value.json
pos_bahrain/pos_bahrain/report/branch_stock_and_value/branch_stock_and_value.py

Duplicated Warehouse wise Item Balance Age and Value report and created new report

Branch stock and value report

---

pos_bahrain/pos_bahrain/report/branch_stock_and_value/branch_stock_and_value.py

float division by zero error in Branch stock value report

float division by zero error solved

---

pos_bahrain/pos_bahrain/report/bank_reconciliation_statement_pb/bank_reconciliation_statement_pb.py
pos_bahrain/pos_bahrain/report/daily_sales_summary/daily_sales_summary.py

bank_reconciliation_statement_pb and Daily Sales Summary Report

bank_reconciliation_statement_pb and Daily Sales Summary Report

---

pos_bahrain/doc_events/bank_reconciliation.py

Fetch GL Payment Entries in Bank Reconsiliation Page

GL Payment Entries in Bank Reconsiliation Page

---

pos_bahrain/api/item.py
pos_bahrain/doc_events/sales_invoice.py
pos_bahrain/hooks.py
pos_bahrain/public/js/pos_page_js.js

Offline POS Pricing Rule

---

pos_bahrain/pos_bahrain/report/vat_on_sales_per_gcc/vat_on_sales_per_gcc.py

Vat Return report txt/clauses error

Vat Return report txt/clauses error

---

pos_bahrain/pos_bahrain/report/vat_on_sales_per_gcc/vat_on_sales_per_gcc.py

Vat reports excluding import from Standard rated

Vat reports excluding import from Standard rated

---

pos_bahrain/doc_events/sales_invoice.py
pos_bahrain/public/js/sales_invoice.js

validation on save when changes of advance amount

validation on save when changes of advance amount

---

pos_bahrain/api/sales_invoice.py
pos_bahrain/doc_events/sales_invoice.py
pos_bahrain/public/js/sales_invoice.js

Removed JV when Credit Note Invoice with advance and rounding in allocated amount

Removed JV when Credit Note Invoice with advance and rounding in allocated amount

---

pos_bahrain/doc_events/sales_invoice.py
pos_bahrain/public/js/sales_invoice.js

Credit Note balance adjustment and Payment Reco changes

Credit Note balance adjustment and Payment Reco changes

---

pos_bahrain/api/price_checker.py
pos_bahrain/pos_bahrain/doctype/price_check/price_check.js

Price check API with warehouse wise stock with item code search

Price check API with warehouse wise stock with item code search

---

pos_bahrain/api/authentication_api.py

Added Logout API

---

pos_bahrain/pos_bahrain/report/batch_wise_expiry_report/batch_wise_expiry_report.py

Batch wise expiry Report qty issue

Batch wise expiry Report qty issue

---

pos_bahrain/api/sales_invoice.py
pos_bahrain/pos_bahrain/doctype/pos_bahrain_settings/pos_bahrain_settings.json
pos_bahrain/public/js/scripts/extensions/stock_entry_item_code.js
pos_bahrain/public/js/stock_entry.js

Added disable_serial_no_and_batch_selector in POS Bahrain Settings

Disabled Stock entry batch selection pop-up by settings

---

pos_bahrain/pos_bahrain/report/item_wise_detailed_sales_register/item_wise_detailed_sales_register.js
pos_bahrain/pos_bahrain/report/item_wise_detailed_sales_register/item_wise_detailed_sales_register.py

The default Supplier does not filter the actual data.

item wise detailed report fixes.

---

pos_bahrain/api/item.py
pos_bahrain/public/js/pos_page_js.js

- Offline POS Serial Number issue Fixed, 
Note : Modification of serial number is not completed yet.

Version 12 - Serial Number

---

pos_bahrain/pos_bahrain/report/item_consumption_report/item_consumption_report.py

Average sales in item consumption report

feat: avg sales in item consumption report

---

pos_bahrain/pos_bahrain/doctype/pos_bahrain_incentive_slab/pos_bahrain_incentive_slab.json
pos_bahrain/pos_bahrain/doctype/pos_bahrain_incentive_slab/pos_bahrain_incentive_slab.py
pos_bahrain/pos_bahrain/doctype/pos_bahrain_settings/pos_bahrain_settings.json
pos_bahrain/pos_bahrain/report/sales_register_for_incentive/sales_register_for_incentive.py

incentive slab change for incetive report

incentive slab change for incetive report

---

pos_bahrain/pos_bahrain/report/sales_register_for_incentive/sales_register_for_incentive.py

After any return, the value of return was increasing instead of decreasing

incentive report -> value after return fix

---

pos_bahrain/pos_bahrain/report/sales_register_for_incentive/sales_register_for_incentive.js
pos_bahrain/pos_bahrain/report/sales_register_for_incentive/sales_register_for_incentive.py

Sales Register for Incentive summary view added and showing records according to sales team

Sales Register for Incentive summary view

---

pos_bahrain/pos_bahrain/report/sales_register_for_incentive/sales_register_for_incentive.py

change Return value to only use net total instead of grand total
Make Return Value in Positive
date : 27th March, 2024

Return Value in Positive in incentive report + other fixes

---

pos_bahrain/api/pos.py
pos_bahrain/pos_bahrain/report/sales_register_for_incentive/sales_register_for_incentive.py

value after retunr fix in Sales Register for Incentive report

value after retunr fix in Sales Register for Incentive report

---

pos_bahrain/pos_bahrain/doctype/pos_closing_voucher/pos_closing_voucher.js
pos_bahrain/public/js/sales_invoice.js

sales invoice total_gross_amount column added and calculations done

sales invoice total_gross_amount

---

pos_bahrain/pos_bahrain/report/batch_wise_expiry_report/batch_wise_expiry_report.js
pos_bahrain/pos_bahrain/report/batch_wise_expiry_report/batch_wise_expiry_report.py

Added item filter in report and fix the values which was not coming in standard Buying and selling.

Batch Wise Expiry Report fix

---

pos_bahrain/pos_bahrain/report/total_stock_balance_custom/total_stock_balance_custom.py

Total Stock Balance Custom was crashing because of some value like batch, fixed

Total Stock Balance Custom

---

pos_bahrain/pos_bahrain/report/sales_register_for_incentive/sales_register_for_incentive.js
pos_bahrain/pos_bahrain/report/sales_register_for_incentive/sales_register_for_incentive.py

sales register for incentive fixes

sales register for incentive fixes

---

pos_bahrain/pos_bahrain/doctype/gl_payment/gl_payment.js

Updated set_calculated field called and moved code from script file to doctype js file

Updated doctype js code with code in scripts and changed set_calculated_field function code

---

pos_bahrain/pos_bahrain/doctype/backported_stock_reconciliation/backported_stock_reconciliation.js
pos_bahrain/pos_bahrain/doctype/backported_stock_reconciliation/backported_stock_reconciliation.py
pos_bahrain/pos_bahrain/doctype/barcode_print/barcode_print.js
pos_bahrain/pos_bahrain/doctype/batch_recall/batch_recall.js
pos_bahrain/pos_bahrain/doctype/branch_barcode_print/branch_barcode_print.js
pos_bahrain/pos_bahrain/doctype/gl_payment/gl_payment.py
pos_bahrain/pos_bahrain/doctype/payment_entry_pb/payment_entry_pb.js
pos_bahrain/pos_bahrain/doctype/pos_bahrain_settings/pos_bahrain_settings.js
pos_bahrain/pos_bahrain/doctype/stock_transfer/stock_transfer.js
pos_bahrain/pos_bahrain/report/stock_report/stock_report.js
pos_bahrain/pos_bahrain/report/stock_report/stock_report.json
pos_bahrain/pos_bahrain/report/stock_report/stock_report.py
pos_bahrain/public/js/batch_quick_entry.js

Fixed barcode print and branch barcode print

Fixed barcode print and branch barcode print form load

---

pos_bahrain/pos_bahrain/report/sales_gross_profit/sales_gross_profit.js
pos_bahrain/pos_bahrain/report/sales_gross_profit/sales_gross_profit.py

Added checkbox for Show Supplier
and column for displaying supplier based on item code

Version 14

---

pos_bahrain/public/js/addons/withBatchPrice.js

Update discount only when discount is blank - withBatchPrice

Update discount only when discount is blank - withBatchPrice
